import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./ThemeProvider";
import { Navbar } from "@/components/navbar/Navbar";
// import { Oxanium } from "next/font/google";
// import { Poppins } from "next/font/google";
// import {Playfair_Display } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
