export const projectData = [
  {
    id: 1,
    name: "EzTicket",
    description:
      "A cinema booking mockup web app powered by TMDB API. Built with React.js, featuring dynamic movie data, state management with Zustand, and clean UI interactions.",
    image: "/3DMarque/movie.png",
    demo: "https://movie-tmdb-beta.vercel.app",
    github: "https://github.com/Jirayut16/movie-tmdb",
    tag: ["React.js", "TypeScript", "Zustand", "Axios", "Tailwind CSS"],
    features: [
      "Dynamic Movie Data",
      "State Management with Zustand",
      "Clean UI Interactions",
      "Responsive Design",
      "Axios for API Calls",
      "Current Date Booking Selection",
    ],
  },
  {
    id: 2,
    name: "JS-Shop ",
    description:
      "A modern fullstack e-commerce app built with React, Express, and MongoDB. Features secure JWT auth, Stripe payments, image uploads via Cloudinary, and user experience in mind.",
    image: "/3DMarque/jsshop.png",
    demo: "https://jsshop.vercel.app/",
    github: "https://github.com/Jirayut16/jsshop",
    tag: [
      "React.js",
      "TypeScript",
      "Tailwind CSS",
      "Node.js",
      "Express.js",
      "MongoDB",
      "JWT",
      "Cloudinary",
      "Redux Toolkit",
    ],
    features: [
      "Authentication & Authorization",
      "Product Management (CRUD System)",
      "Admin Dashboard",
      "User Profile Management",
      "Cart & Checkout System",
      "Stripe Payment Integration",
      "Responsive Design",
      "Order History & Tracking",
      "And many more...",
    ],
  },
  {
    id: 3,
    name: "Today Blog",
    description:
      "A lightning-fast static blog built with Astro Framework. Optimized for performance and SEO, scoring a perfect 100 on Google PageSpeed across all metrics.",
    image: "/3DMarque/blog.png",
    demo: "https://today-blog-rouge.vercel.app/",
    github: "https://github.com/Jirayut16/today-blog",
    tag: ["Astro", "Markdown", "TypeScript", "Tailwind CSS"],
    features: [
      "Static Site Generation (SSG)",
      "Perfect 100 PageSpeed Score",
      "SEO Optimized",
      "Markdown Blog Support",
      "Blazing-fast Load Time",
      "Responsive & Accessible Design",
    ],
  },
  {
    id: 4,
    name: "BetterAuth",
    description:
      "A secure and extensible authentication system built with BetterAuth. Supports email/password and social login via Google and GitHub, with session stored in PostgreSQL using Prisma.",
    image: "/3DMarque/better-auth.png",
    demo: "https://better-auth-orcin.vercel.app/",
    github: "https://github.com/Jirayut16/better-auth",
    tag: [
      "BetterAuth",
      "Next.js",
      "TypeScript",
      "Prisma",
      "PostgreSQL",
      "Arcjet",
      "React-hook-form",
      "Zod",
    ],
    features: [
      "Email & Password Authentication",
      "Email Verification & Password Reset",
      "Email filtering with Arcjet",
      "Social Login with Google and GitHub",
      "Secure Cookie-based Session Management",
      "User Data Stored with Prisma + PostgreSQL",
    ],
  },

  {
    id: 5,
    name: "Food Landing Page",
    description:
      "A modern food landing page template built with Next.js, styled using Tailwind CSS and shadcn/ui, and animated with Framer Motion for delightful interactions.",
    image: "/3DMarque/food.png",
    demo: "https://food-landing-page-azure.vercel.app/",
    github: "https://github.com/Jirayut16/food-landing-page",
    tag: [
      "Next.js",
      "Tailwind CSS",
      "Framer Motion",
      "TypeScript",
      "Shadcn/ui",
    ],
    features: [
      "Responsive Design",
      "Dark Mode",
      "Framer Motion Animations",
      "UI Components with shadcn/ui",
      "SEO & Performance Optimized",
    ],
  },
  {
    id: 6,
    name: "SaaS Landing Page",
    description:
      "A modern SaaS landing page template built with Next.js, styled using Tailwind CSS and shadcn/ui, with interactive animations powered by Framer Motion.",
    image: "/3DMarque/saas.png",
    demo: "https://saas-landing-page-nine-zeta.vercel.app/",
    github: "https://github.com/Jirayut16/saas-landing-page",
    tag: [
      "Next.js",
      "Tailwind CSS",
      "Framer Motion",
      "TypeScript",
      "Shadcn/ui",
    ],
    features: [
      "Responsive Design",
      "Dark Mode",
      "Framer Motion Animations",
      "Pricing & Testimonials Display",
      "SEO & Performance Optimized",
    ],
  },
  {
    id: 7,
    name: "My Portfolio",
    description:
      "A modern and responsive personal portfolio website built with Next.js, styled using Tailwind CSS, and enhanced with smooth animations from Framer Motion.",
    image: "/3DMarque/saas.png",
    demo: "#",
    github: "https://github.com/Jirayut16/portfolio",
    tag: [
      "Next.js",
      "Tailwind CSS",
      "Framer Motion",
      "TypeScript",
      "Shadcn/ui",
    ],
    features: ["Responsive Design", "Smooth Animations", "Dark Mode"],
  },

  {
    id: 8,
    name: "Todolist",
    description:
      "A clean and responsive todolist app. Built with React and TypeScript. Features include task creation, editing, deletion, and local storage persistence.",
    image: "/3DMarque/todo.png",
    demo: "https://jirayut-todolist-app.vercel.app/",
    github: "https://github.com/Jirayut16/todolist-app",
    tag: ["React.js", "TypeScript", "Tailwind CSS", "SweetAlert"],
    features: [
      "Task Create, Edit, Delete",
      "Responsive UI Design",
      "Local Storage Persistence",
      "SweetAlert for Notifications",
      "Dark Mode Toggle",
    ],
  },
];
